version: '3.7'

networks:
  php-test-db: #name network for test database
    external: true
  internal:
    external: false

services:

  php-fpm:
    image: php-docker:latest
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}"
    networks:
      - internal
      - php-test-db

  nginx:
    image: nginx:alpine
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "9990:80"
    networks:
      - internal



  #  db:
  #    image: mariadb:latest
  #    environment:
  #      - MYSQL_DATABASE=symfony
  #      - MYSQL_USER=appuser
  #      - MYSQL_PASSWORD=apppassword
  #      - MYSQL_ROOT_PASSWORD=secret
  #    ports:
  #      - "3306:3306"
  #    networks:
  #      - internal

