version: "3.7"

networks:
  traefik-net: #name network for traefik
    external: true
  internal:
    external: false

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./prod/nginx/conf.d:/etc/nginx/conf.d
      - ./prod/nginx/.htpasswd:/etc/nginx/.htpasswd
    #      - ./devops/prod/nginx/logs:/var/log/nginx/
    networks:
      - internal
      - traefik-net
    deploy:
      labels:
        traefik.backend: "master.express"
        traefik.frontend.rule: "Host:master.express.nikon.host"
        traefik.docker.network: "traefik-net"
        traefik.port: "80"
      replicas: 4
      update_config:
        parallelism: 2

  express:
    image: "nikon5070/express-hello:master"
#    image: "${CONTAINER_PROD}"
    networks:
      - internal
    deploy:
      replicas: 4
      update_config:
        parallelism: 2

