name: Dev

on:
  pull_request:
    branches:
      - "master"
env:
  NAME_PROJECT: ${{ secrets.NAME_PROJECT }}
  CONTAINER_TEST: "registry.d.ratio.bz/symfony"

  DOCKER_REGISTY_HOST: ${{ secrets.DOCKER_REGISTY_HOST }}
  DOCKER_REGISTY_LOGIN: ${{ secrets.DOCKER_REGISTY_LOGIN }}
  DOCKER_REGISTY_PASS: ${{ secrets.DOCKER_REGISTY_PASS }}
  AUTH_BASIC: ${{ secrets.AUTH_BASIC }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: set auth basic
        run: |
          echo $AUTH_BASIC > ./devops/nginx/.htpasswd
      - name: docker login
        run: |
          echo $DOCKER_REGISTY_PASS | docker login $DOCKER_REGISTY_HOST -u $DOCKER_REGISTY_LOGIN --password-stdin
      - name: build docker image
        run: |
          docker build -t $CONTAINER_TEST:${GITHUB_HEAD_REF} -f ./devops/Dockerfile .
      - name: push docker images in registy
        run: |
          docker push $CONTAINER_TEST:${GITHUB_HEAD_REF}
      - name: pull docker images with registy
        run: |
          docker pull $CONTAINER_TEST:${GITHUB_HEAD_REF}

  migrations:
    runs-on: self-hosted
    needs: build
    steps:
      - name: migrations schemes
        run: |
          docker run --name ${NAME_PROJECT}_${GITHUB_HEAD_REF}_migrations \
              --rm \
              --network php-test-db \
              -e DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME} \
              $CONTAINER_TEST:${GITHUB_HEAD_REF} \
              wait-for-it db:3306 -- php bin/console doctrine:migrations:migrate

  tests:
    runs-on: self-hosted
    needs: migrations
    steps:
      - name: phpunit tests
        run: |
          docker run --name ${NAME_PROJECT}_${GITHUB_HEAD_REF}_test \
              --rm \
              --network php-test-db \
              -e DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME} \
              $CONTAINER_TEST:${GITHUB_HEAD_REF} \
              php bin/phpunit

  dev-deploy:
    needs: tests
    runs-on: self-hosted

    steps:
      - name: docker dev stack
        run: |
          docker stack deploy --compose-file ./devops/docker-compose-dev.yml ${NAME_PROJECT}_${GITHUB_HEAD_REF}

#  clear-unused-docker-containers:
#    needs: [dev-deploy]
#    runs-on: self-hosted
#
#    steps:
#      - name: clear
#        run: |
#          bash ./devops/clean.sh
